# Hexo Configuration
## Docs: http://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: RugbyProf Blog
subtitle: Code Code Code
description: Computer Stuff
author: Rugbyprof
author_title: 'Web Developer & Designer'
avatar: css/images/avatar.png
location: 'Wichita Falls, TX'
follow: https://github.com/rugbyprof/
email: # Your email (Used to show Gravatar).
language: en
timezone:
since: 2015 # The start year showing in your copyright section.

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://rugbyprof.github.io/
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 6
pagination_dir: page

# Extensions
## Plugins: https://github.com/hexojs/hexo/wiki/Plugins
## Themes: https://github.com/hexojs/hexo/wiki/Themes
theme: hueman

# Disqus
# disqus_shortname: hexo-theme-icarus

# DuoShuo
# duoshuo_shortname: hexo-theme-icarus

# Swiftype
# swiftype_install_key: XXX_XXXXXXXXXXXXXXXX

# Deployment
## Docs: http://hexo.io/docs/deployment.html
deploy:
  type: git
  repository: https://github.com/rugbyprof/rugbyprof.github.io
  branch: gh-pages
  
################################################################

# Header
menu:
  Home: /
  Categories:
  - 5143-OpSys
  - 2143-OOP
  About: /about/index.html

# Content
fancybox: true

# Thumbnail
thumbnail: false

# Scroll Loading
scrollLoading: true

# Sidebar
# social_links:
#   twitter:
#   facebook:
#   google_plus:
#   weibo:
#   rss:
widgets:
- recent_posts
- category
- archive
- tag
- tagcloud
- links

# Links
links:
  Hexo: http://hexo.io

# Miscellaneous
google_analytics:
favicon: /favicon.png

logo:
  url: https://s3.amazonaws.com/f.cl.ly/items/2l0K2C3m070x1R160u1M/ComputerScience.small.png
  width: 86px
  height: 100px